### ISSUE TITLE
Quarkus 3.16 ClassGraph error

### ISSUE THREAD

**Issue by kdubb** [neo4j/neo4j-ogm-quarkus#403]
Updating to 3.16.1 produces the following exception during startup:

```
Caused by: java.lang.RuntimeException: Exception while calling findClassLoaderOrder for nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler
        at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:239)
        at nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:277)
        at io.github.classgraph.Scanner.<init>(Scanner.java:170)
        at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1562)
        at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1590)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1615)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1654)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1667)
        at org.neo4j.ogm.metadata.DomainInfo.useClassgraph(DomainInfo.java:134)
        at org.neo4j.ogm.metadata.DomainInfo.findClasses(DomainInfo.java:119)
        at org.neo4j.ogm.metadata.DomainInfo.create(DomainInfo.java:92)
        at org.neo4j.ogm.metadata.MetaData.<init>(MetaData.java:65)
        at org.neo4j.ogm.session.SessionFactory.<init>(SessionFactory.java:124)
        at org.neo4j.ogm.session.SessionFactory.<init>(SessionFactory.java:110)
        at org.neo4j.ogm.quarkus.runtime.Neo4jOgmRecorder.initializeSessionFactory(Neo4jOgmRecorder.java:65)
        at io.quarkus.deployment.steps.Neo4jOgmProcessor$createSessionFactory1383093778.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.Neo4jOgmProcessor$createSessionFactory1383093778.deploy(Unknown Source)
        ... 11 more
```

**Comment by michael-simons** [comment]
Hey, thank you! We haven't upgraded this extension to 3.16, so there might be indeed issues.

**Comment by michael-simons** [comment]
Can reproduce.

**Comment by michael-simons** [comment]
I think we must raise this with https://github.com/classgraph/classgraph

**Comment by michael-simons** [comment]
Na, someone else did.

https://github.com/classgraph/classgraph/issues/891

As Neo4j-OGM manages this dependency, I am gonna close that issue here. Thanks again!

**Comment by michael-simons** [comment]
Fixed with https://github.com/neo4j/neo4j-ogm-quarkus/releases/tag/3.10.0

Thanks again for bringing the whole thing to my attention.
